name: tssc-tool-selenium-pr
on:
  pull_request:
    paths:
      - tssc-tool-selenium/**
jobs:
  build:
    env:
      context: tssc-tool-selenium
      image_name: tssc-tool-selenium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check and verify version.json
        id: check_version
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
          echo $(jq -r '.version' ${context}/version.json)
      - name: Build image
        uses: docker/build-push-action@v1
        with:
          path: ${{ env.context }}
          push: false
          repository: ${{ env.image_name }}
          tags: ${{ steps.check_version.outputs.IMAGE_TAGS }}
      - name: Test image
        run: |
          echo "Running: docker run ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} java -version"
          docker run -u 1001 ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} java -version
          echo "Running: docker run ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} mvn --version"
          docker run -u 1001 ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} mvn --version
          echo "Running: docker run ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} -u 1001 touch ~/tssc/.m2/test.txt"
          docker run -u 1001 ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} touch /home/tssc/.m2/test.txt 
